### PR TITLE
sla applied at update for first reply time

### PR DESCRIPTION
**Pull request by fivetran-joemarkiewicz**
**Are you a current Fivetran customer?** 

Fivetran created PR

**What change(s) does this PR introduce?** 

This PR updates logic within `int_zendesk__sla_policy_applied` to more accurately reflect the `sla_applied_at` time for `first_reply_time` sla's. Per [Zendesk's documentation](https://support.zendesk.com/hc/en-us/articles/4408821871642-Understanding-ticket-reply-time) the `first_reply_time` sla is set at the creation of the ticket, even if the sla is applied after creation.

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [X] No  (please provide explanation how the change is non breaking below.)

This PR only introduces a logic update to more accurately map to Zendesk's calculation and is not a breaking change.

**Is this PR in response to a previously created Issue**

- [X] Yes, Issue #51 
- [ ] No 

**How did you test the PR changes?** 

 
- [ ] CircleCi  
- [ ] Other (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 
- [X] BigQuery
- [X] Redshift
- [X] Snowflake
- [X] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
🧧 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by jackiexsun** [comment]
I ran the package locally and updated our Support Looker models to pull from my local version of the package. The figures are still not correct (more incorrect for historicals, which may be due to the Sara Leon user role issue)
Screen Shot 2021-11-17 at 12 45 12 PM

Screen Shot 2021-11-17 at 12 55 22 PM

**Comment by fivetran-joemarkiewicz** [comment]
@jackiexsun do you have a reference for what the totals should be in aggregate?

**Comment by jackiexsun** [comment]
Q1 (this is filtering on first_reply_time and Starter / Standard SLA and Enterprise SLA and ticket group = 'Support', 'Sales & CS', & 'Marketing' & 'Finance & Ops' & 'DB, Events, & Files'
Screen Shot 2021-11-18 at 2 47 30 PM

Q2
Screen Shot 2021-11-18 at 2 49 50 PM

Q3
Screen Shot 2021-11-18 at 2 50 18 PM

Q4 (as of today Nov 18)
Screen Shot 2021-11-18 at 2 50 43 PM

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @jackiexsun this is a huge help! Let me look more into this! 👀

**Comment by jackiexsun** [comment]
For reference, here is a CSV by ticket ID and SLA breach status for tickets created between Feb 1 2021 and April 30 202
[SLAs_SLA_achievement_rate_by_ticket_ID_default_JS_11192021_0422.csv](https://github.com/fivetran/dbt_zendesk/files/7566545/SLAs_SLA_achievement_rate_by_ticket_ID_default_JS_11192021_0422.csv)
1

**Comment by fivetran-joemarkiewicz** [comment]
@jackiexsun thanks for testing out the PR and sharing the additional info on how the totals weren't tying out.

I was able to look a bit more into the code and found there was a `left join` that was missing the assignment of the `sla_policy_name`. Therefore, there would be a number of sla tickets that didn't have a name associated with them and then would be exclude in the aggregate calculation. I have since pushed a change to the working branch I highlighted in the PR and have found that for the date range 02-01-2021 → 04-30-2021 the dbt package output and the Zendesk output nearly match!

Essentially I found that there were 78 mismatches, 77 were related to the first responder agent leaving the company and 1 was mismatched because the ticket actually had 2 sla targets set and Zendesk only captured the breach event.

It would be great if you had time to rerun the working branch and see if the aggregate numbers work themselves out (taking into account the agents leaving the company issue).

**Comment by jackiexsun** [comment]
Prod 
Screen Shot 2021-12-13 at 10 37 20 AM

Bugfix branch 
Screen Shot 2021-12-13 at 10 40 31 AM

It looks like the figures are definitely closer. I checked the SLA figure in Zendesk and it is around 97.7%. Going to find some examples of tickets where the SLAs are mismatched.

**Comment by jackiexsun** [comment]
Actually! I realized that when the SLA breach timestamp hasn't passed yet, Zendesk reports these tickets as achieving the SLA whereas our modeling (on top of the package) would report this as breaching the SLA. When I modify our model to match Zendesk, I get all breached tickets matching for Q4 and the overall SLA achievement figure is 98%.

**Comment by jackiexsun** [comment]
Overall looks good, just one question. I noticed for ticket_id = 47927 (and others) there are two SLA targets for the same policy
Screen Shot 2021-12-13 at 1 57 32 PM

Searching in Zendesk, it _looks_ like there should only be one SLA target for the same policy / metric. Based on the "urgent" priority I think the target for this ticket should be 240. 
Screen Shot 2021-12-13 at 2 00 59 PM

Query for these duplicates sla policies
```
select ticket_id, sla_policy_name, metric, count(*)
from `digital-arbor-400.z_dbt_jackie.zendesk__sla_policies`
where metric = 'first_reply_time'
group by 1, 2, 3
having count(*) > 1
```

I think we should take the most recently applied SLA policy as the overall SLA policy for that ticket for 'first reply time' (and to your point, it should still be taken from the created_date of the ticket, even if the applied date is later). I believe for 'next reply time' this can be applied multiple times.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @jackiexsun thanks for looking further into this and checking the updates seem to tie out!

I agree with your statement on the `first_reply_time` sla's and how it is quite confusing that there are multiple records for tickets `first_reply_time` sla. Do you know of any reason why a ticket would or should have multiple `first_reply_time` slas? If not, I think it is appropriate to limit to just the most recent like you have suggested.

**Comment by jackiexsun** [comment]
I am not 100% sure why tickets would have changing SLAs, but my guess is
that if the ticket priority changes, then the SLA would also change because
the SLA is based on customer tier and priority.

**Review by jackiexsun — APPROVED** [review]
Looks good!

**Pull request merged**
