### PR TITLE
preserve whitespace in int_zendesk__field_history

### PR DESCRIPTION
**Pull request by bcolbert978**
**Please provide your name and company**
Brad Colbert, Fivetran 👋 

**Link the issue/feature request which this PR is meant to address**
#105 

**Detail what changes this PR introduces and how this addresses the issue/feature request linked above.**
Removes the whitespace-handling from the jinja function at the beginning of the script. Doing so causes the compiled SQL to maintain whitespace which may be unnecessary/unaesthetic but which definitely runs as valid SQL, without risk of the non-jinja comment joining the the actual SQL code.

**How did you validate the changes introduced within this PR?**
dbt run works.

**Which warehouse did you use to develop these changes?**
BigQuery

**Did you update the CHANGELOG?**

- [ ] Yes

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes

**Provide an emoji that best describes your current mood**
 
:white_square_button:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @bcolbert978! At first glance this PR looks good to me. However, there are a few minor updates I would like to apply before merging this in order to be consistent with our updates (ie. update the changelog, increase version, etc.). Are you comfortable if I edit your branch directly to make these changes for you? No changes will be applied to your .sql file changes.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks @bcolbert978! I will update your PR to include some changes! Also, if you are not on a tight schedule I may plan to batch your updates with the upcoming release that will also include the fix for Issue #107. This may delay the release for another week or so.

Let me know if that timeline is appropriate. Otherwise if this is needed ASAP I can roll this out in a patch release early next week.

**Comment by bcolbert978** [comment]
I think my delayed reaction speaks for itself 🙃 feel free to roll in to your other changes.

**Review by fivetran-joemarkiewicz — APPROVED** [review]
lgtm!

FYI @fivetran-jamie can we regen the docs. Since we made the code change even though it is super small we should still update them to reflect the current codebase.

**Pull request merged**
